TeselaGen/tg-oss

packages/ove/cypress/e2e/dialogs.spec.js
packages/ove/src/helperComponents/AddOrEditAnnotationDialog/index.js
packages/ove/src/withEditorProps/index.js

https://github.com/TeselaGen/tg-oss/issues/22

fixing annotation range issue and adding test 

---

packages/ui/cypress/e2e/tgSelect.spec.js
packages/ui/src/TgSelect/index.js

Updated reorder function to get most relevant results first

Reorder tgSelect results

---

packages/sequence-utils/src/getAminoAcidStringFromSequenceString.js

Fixes https://github.com/TeselaGen/tg-oss/pull/50

Fixed condition for removing *

---

packages/bio-parsers/src/genbankToJson.js
packages/bio-parsers/test/genbankToJson.test.js

closes #71

---

packages/bio-parsers/project.json
packages/bounce-loader/project.json
packages/file-utils/project.json
packages/ove/project.json
packages/range-utils/project.json
packages/sequence-utils/project.json
packages/ui/project.json
tools/scripts/publish.mjs

feat: Add publishing of beta versions

---

packages/ove/src/index.js

Hi @tnrich, I would like to use getStructuredBases somewhere in my code, is it possible to add it as one of the exported functions?

OVE: export getStructuredBases

---

packages/ove/demo/src/exampleData/exampleSequenceData.js
packages/ove/src/CircularView/Primer.js
packages/ove/src/RowItem/StackedAnnotations/PointedAnnotation.js
packages/ove/src/utils/editorUtils.js

closes #88

---

packages/ove/src/RowItem/StackedAnnotations/PointedAnnotation.js

fixes #88 in Linear Map, followup to #89
@tnrich

fixes #88 in Linear Map, followup to #89

---

packages/ove/cypress/e2e/editor.spec.js
packages/ove/demo/src/EditorDemo/index.js
packages/ove/src/Editor/index.js
packages/ove/src/withEditorInteractions/index.js

double click event hooks

---

packages/ove/cypress/e2e/editor.spec.js
packages/ove/demo/src/EditorDemo/index.js
packages/ove/src/Editor/index.js

Panel tab on close hook

---

packages/ui/src/TgSelect/index.js

TgSelect empty option

---

packages/ui/cypress/e2e/EditableCellTable.spec.js
packages/ui/cypress/e2e/upload.spec.js
packages/ui/demo/src/examples/EditableCellTable.js
packages/ui/demo/src/examples/FormComponents.js
packages/ui/src/TgSuggest/index.js

Fixes test on the ui:
- Fixing editableCellTable tests
- Fixing formComponents tests
@tnrich

Fix editable cell table tests

---

packages/ui/demo/src/examples/FormComponents.js
packages/ui/src/FormComponents/FormSeparator.js
packages/ui/src/FormComponents/style.css
packages/ui/src/index.js

feat: Add form separator component

---

packages/ove/cypress/e2e/globalDialog.spec.js
packages/ove/src/GlobalDialogUtils.js

@tnrich
currently if we open two Editor, and open dialog from one Editor and close the dialog, then we can not open any dialog from another Editor.

fix open dialog issue for multiple Editor

---

packages/ove/demo/src/AlignmentDemo.js
packages/ove/demo/src/index.js
packages/ove/demo/src/utils/useToggle.js
packages/ui/src/DataTable/utils/queryParams.js

refactor: AlignmentDemo

---

package.json
packages/ove/src/AlignmentView/index.js
packages/ove/src/withEditorInteractions/index.js
yarn.lock

Remove clipboard package
@tnrich

fix: removeClipboardPackage

---

packages/ove/src/AlignmentView/index.js
packages/ove/src/RowItem/Caret/index.js

Alignment view refactor

---

packages/ove/src/withEditorInteractions/index.js

@tnrich
The copy functions are broken by https://github.com/TeselaGen/tg-oss/pull/118, this PR is to fix it.

fix copy sequence

---

packages/ui/cypress/e2e/dataTable.spec.js
packages/ui/src/DataTable/SearchBar.js

@tnrich
Issue: the search button is not working
Fixed:

fix search button function

---

packages/ove/src/helperComponents/PropertiesDialog/TranslationProperties.js

fix crash issue when showing translations

---

packages/ui/src/FormComponents/Uploader.js

Fix: blur uploader on drop so that enter will not retrigger file select

---

packages/ove/README.md

@tnrich
Issue #160
Fixed the invalid link of Labii.

Fixed the invalid links of Labii

---

packages/ui/src/AdvancedOptions.spec.js
test-setup.js

Fix advancedOptions test in UI

---

packages/sequence-utils/src/threeLetterSequenceStringToAminoAcidMap.js

add more codons like codon ‘TCK’ should be serine, 'uaa' should be stop codon
@tnrich

support more codons
